on: pull_request

jobs:
  test_comment_pr:
    name: (NRT) Comment PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: ./
        with:
          message: |
            Current branch is `${{ github.head_ref }}`.
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            <!--- thollander/actions-comment-pull-request "comment_tag" --->
          comment_includes: <!--- thollander/actions-comment-pull-request "comment_tag" --->
          reactions: eyes, rocket